developer:
  build: .
  ports:
   - "8080:8080"
   - "8787:8787"
   - "8443:8443"
  volumes:
   - $OVIRT_ENGINE_SRC:/home/ovirt/src/ovirt-engine
   - /tmp/.X11-unix:/tmp/.X11-unix
   - $HOME/.Xauthority:/home/ovirt/.Xauthority
  links:
   - db
  working_dir: /home/ovirt/src
  user: ovirt
  environment:
    - DISPLAY
  entrypoint: /bin/bash

db:
  image: centos/postgresql
  hostname: db
  volumes_from:
   - db_data

db_data:
  build: db/.
